version: 0.0.0.{build}

skip_tags: true
configuration: Release

os: Visual Studio 2017

before_build:
- cmd: >-
    cd Stryker.NET

    nuget install MSBuild.SonarQube.Runner.Tool -Version 1.0.0 -OutputDirectory packages

    nuget install JetBrains.dotCover.CommandLineTools -Version 2016.3.20170126.124346 -OutputDirectory packages
    
    dotnet restore
    
    InitializeSonarqubeAnalysis.bat
    
build:
  verbosity: minimal

after_build:
- cmd: >-
    RunDotCoverCodeCoverageSession.bat

    RunSonarqubeAnalysis.bat
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path TestResults.trx))
test: off